### ISSUE TITLE
Notation "≡" is not defined.

### ISSUE THREAD

**Issue by krtab** [OCamlPro/verification_for_dummies#2]
https://github.com/OCamlPro/verification_for_dummies/blob/c17f56cba61c959371a63ea694feb3c328dfe45f/src/smt/readme.md?plain=1#L175-L176

It is somewhat easily inferred from context but could be explicitly defined.

**Comment by AdrienChampion** [comment]
How about

https://github.com/OCamlPro/verification_for_dummies/blob/edb533859bd7aae3974b65c85cbb0002cd069c03/src/smt/readme.md?plain=1#L48-L64

**Comment by krtab** [comment]
Woops.
Sorry about that!

**Comment by AdrienChampion** [comment]
> Woops. Sorry about that!

What ? No no no @krtab, I just added this bit in a separate branch that I plan to merge, I was asking for your opinion 🐱

**Comment by krtab** [comment]
Ah!

Then it looks good to me, except for the missing "in" line 55 ("lives **in** the world").
